// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"post-service/internal/biz"
	"post-service/internal/conf"
	"post-service/internal/data"
	"post-service/internal/job"
	"post-service/internal/server"
	"post-service/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confBiz *conf.Biz, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	postRepo := data.NewPostRepo(dataData, logger)
	postUsecase := biz.NewPostUsecase(confBiz, postRepo, logger)
	postSrvService := service.NewPostSrvService(postUsecase, logger)
	grpcServer := server.NewGRPCServer(confServer, postSrvService, logger)
	dataPostRepo := data.NewPostRepoForJob(dataData, logger)
	jobRepo := job.NewJobRepo(confData, dataPostRepo, dataData, logger)
	app := newApp(logger, grpcServer, jobRepo)
	return app, func() {
		cleanup()
	}, nil
}
